apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: ghcr.io/rudolfratusinski/hello-world:v1.0.4
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: hello-world-env-file
          mountPath: /app/.env
          readOnly: true
      serviceAccountName: rds-iam-auth
      volumes:
      - name: hello-world-env-file
        configMap:
          name: aws-infra-data-config